import { defineCollection, defineConfig, s } from 'velite';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { readdirSync, existsSync } from 'node:fs';
import path from 'node:path';

const posts = defineCollection({
  name: 'Post',
  pattern: 'posts/**/meta.json',
  schema: s.object({
    date: s.isodate(),
    tags: s.array(s.string()).default([]),
    series: s.string().optional(),
    featured: s.boolean().default(false),
    type: s.string().default('DeepDive'),
    status: s.enum(['published', 'draft']).default('published'),
  }).transform((data, { meta }) => {
    const parts = meta.path.split('/');
    return { ...data, slug: parts[parts.length - 2] };
  }),
});

const postI18n = defineCollection({
  name: 'PostI18n',
  pattern: 'posts/**/zh.mdx',
  schema: s.object({
    title: s.string(),
    excerpt: s.string(),
    plain: s.raw(),
    code: s.mdx(),
    metadata: s.metadata(),
  }).transform((data, { meta }) => {
    const parts = meta.path.split('/');
    return { ...data, slug: parts[parts.length - 2], readMinutes: Math.max(1, Math.round(data.metadata.readingTime || 1)) };
  }),
});

type I18nItem = {
  title: string;
  excerpt: string;
  readMinutes: number;
  slug: string;
  code: string;
};

export default defineConfig({
  root: 'content',
  collections: { posts, postI18n },
  prepare: async (data) => {
    const contentDir = path.resolve('content/posts');

    const allDirs = readdirSync(contentDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);

    const i18nBySlug = new Map<string, I18nItem>();

    for (const item of data.postI18n) {
      const slug = item.slug;

      if (!slug) {
        continue;
      }

      i18nBySlug.set(slug, {
        title: item.title,
        excerpt: item.excerpt,
        readMinutes: item.readMinutes,
        slug,
        code: item.code,
      });
    }

    const published: Array<{
      slug: string;
      date: string;
      tags: string[];
      series: string | null;
      featured: boolean;
      type: string;
      status: string;
      title: string;
      excerpt: string;
      readMinutes: number;
      code: string;
    }> = [];

    for (const dirName of allDirs) {
      const metaPath = path.join(contentDir, dirName, 'meta.json');
      if (!existsSync(metaPath)) {
        continue;
      }

      const metaRaw = await readFile(metaPath, 'utf8');
      const meta = JSON.parse(metaRaw) as {
        date: string;
        tags?: string[];
        series?: string;
        featured?: boolean;
        type?: string;
        status?: string;
      };

      if (meta.status === 'draft') {
        continue;
      }

      const i18n = i18nBySlug.get(dirName);
      if (!i18n) {
        continue;
      }

      published.push({
        slug: dirName,
        date: meta.date,
        tags: meta.tags ?? [],
        series: meta.series ?? null,
        featured: meta.featured ?? false,
        type: meta.type ?? 'DeepDive',
        status: meta.status ?? 'published',
        title: i18n.title,
        excerpt: i18n.excerpt,
        readMinutes: i18n.readMinutes,
        code: i18n.code,
      });
    }

    published.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    const searchIndex = published.map((post) => {
      return {
        slug: post.slug,
        title: post.title,
        excerpt: post.excerpt,
        tags: post.tags,
        date: post.date,
        readMinutes: post.readMinutes,
        series: post.series,
        featured: post.featured,
        searchText: [post.title, post.excerpt, ...post.tags].join(' ').toLowerCase(),
      };
    });

    const compositePosts = published.map((post) => ({
      slug: post.slug,
      date: post.date,
      tags: post.tags,
      series: post.series,
      featured: post.featured,
      type: post.type,
      status: post.status,
      title: post.title,
      excerpt: post.excerpt,
      readMinutes: post.readMinutes,
      code: post.code,
    }));

    const outputDir = path.resolve(process.cwd(), '.velite');
    const publicDir = path.resolve('public');
    const libDir = path.resolve('lib');

    await mkdir(outputDir, { recursive: true });
    await mkdir(publicDir, { recursive: true });

    await writeFile(path.join(outputDir, 'searchIndex.json'), JSON.stringify(searchIndex, null, 2), 'utf8');
    await writeFile(path.join(publicDir, 'searchIndex.json'), JSON.stringify(searchIndex, null, 2), 'utf8');
    await writeFile(path.join(outputDir, 'compositePosts.json'), JSON.stringify(compositePosts, null, 2), 'utf8');
    await writeFile(path.join(libDir, '__generated_posts.ts'), `// Auto-generated by velite, do not edit
import type { CompositePost } from '@/types/blog';

const posts: CompositePost[] = ${JSON.stringify(compositePosts, null, 2)} as CompositePost[];

export default posts;
`, 'utf8');
  },
});
